# Basic Configuration
title: "Muhuyi Erick"
tagline: "Data Analyst | Researcher | Statistician"
description: "Research & Data Analyst portfolio"
url: "https://muhuyierick.github.io"
baseurl: ""
lang: "en"
timezone: "Africa/Nairobi"

# Theme
remote_theme: cotes2020/jekyll-theme-chirpy

# Author
author:
  name: "Muhuyi Erick"
  email: "muhuyierick467@gmail.com"

# Social Media
social:
  name: Muhuyi Erick
  email: muhuyierick467@gmail.com
  links:
    - https://twitter.com/erick_muhuyi
    - https://github.com/muhuyierick
    - https://www.linkedin.com/in/muhuyi-erick

# Navigation
tabs:
  home: /
  archives: /archives/
  categories: /categories/
  tags: /tags/
  about: /about/

# Avatar
avatar: "/assets/profile.png"

# Build settings
permalink: /posts/:title/
paginate: 10

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: ""
      type: tabs
    values:
      layout: page

# Exclude unnecessary files
exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - package.json
  - package-lock.json
  - node_modules
