# Basic Configuration
title: "Muhuyi Erick"
tagline: "Data Analyst | Researcher | Statistician"
description: "Research & Data Analyst portfolio"
url: "https://muhuyierick.github.io"
baseurl: ""
lang: "en"
timezone: "Africa/Nairobi"

# Theme
remote_theme: cotes2020/jekyll-theme-chirpy

# Author
author:
  name: "Muhuyi Erick"
  email: "muhuyierick467@gmail.com"
  twitter: "erick_muhuyi"
  github: "muhuyierick"

# Navigation
tabs:
  home: /
  archives: /archives/
  categories: /categories/
  tags: /tags/
  about: /about/

# Avatar
avatar: "/assets/profile.png"

# Build settings
permalink: /posts/:title/
paginate: 10
paginate_path: /page/:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
